language: node_js

node_js:
  - 8
  - 6
  - 4

env:
  global:
    - export COVERALLS_SERVICE_NAME=travis-ci
    - export COVERALLS_REPO_TOKEN=wEPmOB8VfKBdChU8hQ9tv9LfkeQHRl16D

branches:
  only:
    - master

script: ./scripts/run-tests.sh

sudo: false

